# Generated by Django 5.1.3 on 2025-01-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
